app/models.py
# File for models/classes
from . import create_app
# from app.models import User,Role,Review
class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from  flask import FlaskForm
from .forms import  TextAreaField,SubmitField,validators

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
# from flask_sqlalchemy import SQLAlchemy
# from flask_login import LoginManager



# Instances of flask extensions
# Instance of LoginManger and using its methods
# login_manager = LoginManager()
# login_manager.session_protection = 'strong'
# login_manager.login_view = 'auth.login'
# bootstrap = Bootstrap()
# db = SQLAlchemy()

def create_app(config_name):
    '''
    Function that takes configuration setting key as an argument
    
    Args:
        config_name : name of the configuration to be used
    '''

    # Initialising application
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])


    # Initialising flask extensions
    # bootstrap.init_app(app)
    # db.init_app(app)
    # login_manager.init_app(app)

    # Regestering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Regestering the auth bluprint
    # from .auth import auth as auth_blueprint
    # app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # Setting config when using an API
    # from .requests import configure_request
    # configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Reviews, User
from .forms import ReviewForm,UpdateProfile
from .. import db
# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home'

    return render_template('index.html', title = title )

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}

    {% include 'navbar.html' %}
    
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>Error Page</h1>
        
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>Home Page</h1>

    </div>

{% endblock %}

app/templates/navbar.html
{% extends 'base.html' %}

<!-- Navbar block -->
{% block navbar %}
    <div class="container">

        <div class="navbar navbar-inverse" role="navigation" >

            <div class="container">

                <div class="navbar-header">

                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">

                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                        {%endif%}
                    </ul>
                    </button>

                    <a href="/" class="navbar-brand">SiteName</a>

                </div>

                <div class="navbar-collapse collapse">

                    <ul class="nav navbar-nav">

                        <li>
                            <a href="/">Home</a>
                        </li>
                        
                    </ul>

                </div>

            </div>

        </div>

    </div>
{% endblock %}